# Wallbox REST Sensor
- platform: rest
  name: Wallbox
  resource: "https://www.solaxcloud.com/proxyApp/proxy/api/getPileInfo?tokenId=!secret solax_token&pileSn=!secret solax_wallbox_sn"
  json_attributes_path: "$.result"
  json_attributes:
    - chargerStatus
    - chargingMode
    - chargingPower
    - chargeEnergy
  value_template: "Active"

# Solax Cloud API v2 (Inverter Data)
- platform: rest
  name: Solax Cloud API
  resource: !secret solax_api_url
  method: POST
  headers:
    Content-Type: "application/json"
    tokenId: !secret solax_token
  payload: !secret solax_api_request_body
  scan_interval: 60
  value_template: "{{ value_json.success }}"
  json_attributes:
    - success
    - exception
    - result
    - code

# Tibber Preise
- platform: rest
  name: Tibber prices
  resource: https://api.tibber.com/v1-beta/gql
  method: POST
  scan_interval: 60
  payload: >
    { "query": "{ viewer { homes { currentSubscription { priceInfo { today { total startsAt } tomorrow { total startsAt }}}}}}" }
  json_attributes_path: "$.data.viewer.homes[0].currentSubscription.priceInfo"
  json_attributes:
    - today
    - tomorrow
  value_template: "Ok"
  headers:
    Authorization: !secret tibber_authorization
    Content-Type: application/json
    User-Agent: REST

# WP Energie integriert
- platform: integration
  source: sensor.wp_gesamtleistung_w_v2
  name: WP Energie integriert roh v2
  unit_time: s
  method: left
  round: 3

# Wallbox Energie integriert
- platform: integration
  source: sensor.wb_leistung_w
  name: WB Energie integriert roh
  unit_time: s
  method: left
  round: 3

# AC-THOR Energie integriert
- platform: integration
  source: number.ac_thor_9s_1_power_ac9
  name: ac_thor_energy_workaround
  unit_prefix: k
  unit_time: h
  method: left
  round: 3
