# WP Energie integriert
- platform: integration
  source: sensor.wp_gesamtleistung_w_v2
  name: WP Energie integriert roh v2
  unit_time: s
  method: left
  round: 3

# Wallbox Energie integriert
- platform: integration
  source: sensor.wb_leistung_w
  name: WB Energie integriert roh
  unit_time: s
  method: left
  round: 3

# AC-THOR Energie integriert
- platform: integration
  source: number.ac_thor_9s_1_power_ac9
  name: ac_thor_energy_workaround
  unit_prefix: k
  unit_time: h
  method: left
  round: 3
