name: Home Assistant Config Check

on:
  push:
    branches:
      - '**'          # alle Branches prüfen
  pull_request:
    branches:
      - main          # PRs auf main prüfen

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create dummy secrets.yaml
        run: |
          cat <<EOF > secrets.yaml
          influxdb_user: dummy
          influxdb_password: dummy
          solax_api_url: "https://dummy.com"
          solax_token: dummy
          solax_sn: dummy
          solax_api_request_body: dummy
          solax_wallbox_sn: dummy
          mypv_token: dummy
          mypv_serial: dummy
          tibber_authorization: dummy
          solax_modbus_ip: dummy
          EOF

      - name: Home Assistant Config Check
        uses: frenck/action-home-assistant@v1
        with:
          path: "."

